name: Build tex and rst

on: 
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        if: github.event_name != 'pull_request'

      - name: Checkout repo for PR
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
        if: github.event_name == 'pull_request'

      - name: Compile ZIPs and Zcash Protocol Specification
        uses: ./.github/actions/render

      - uses: EndBug/add-and-commit@v9.1.3
        with:
          add: 'protocol/*.pdf *.html'
          default_author: github_actions
